spring.application.name=web

spring.datasource.url=jdbc:sqlite:forenstorage.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
# SQLite does not support Hibernate's ALTER TABLE unique-constraint updates.
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=SKIP
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
