spring.application.name=web

spring.datasource.url=jdbc:sqlite:forenstorage.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update